"""
Example 01 — Discovering and connecting to instruments over LAN and USB.

This is the starting point for any VISA-based instrument session.
Run this first to confirm VISA sees your instruments before using the drivers.

Requirements: pyvisa, NI-VISA or Keysight IO Libraries Suite installed.
"""

import pyvisa

# ── List all visible resources ────────────────────────────────────────────────
rm = pyvisa.ResourceManager()
resources = rm.list_resources()
print("Visible VISA resources:")
for r in resources:
    print(" ", r)

# ── LAN (TCPIP) connection — Keysight scope (HiSLIP) ─────────────────────────
# HiSLIP is the modern LAN instrument protocol (faster, lower latency than VXI-11).
# Replace the IP with your instrument's actual address.
SCOPE_ADDRESS = "TCPIP0::192.168.1.100::hislip0::INSTR"

scope_resource = rm.open_resource(SCOPE_ADDRESS)
scope_resource.timeout = 60000  # ms — scope measurements can be slow
print("Scope IDN:", scope_resource.query("*IDN?").strip())

# ── LAN (TCPIP) connection — R&S signal generator (VXI-11) ───────────────────
SIGGEN_ADDRESS = "TCPIP0::192.168.1.101::inst0::INSTR"

siggen_resource = rm.open_resource(SIGGEN_ADDRESS)
siggen_resource.timeout = 50000
print("Signal Gen IDN:", siggen_resource.query("*IDN?").strip())

# ── USB connection — Keithley supply (USBTMC) ─────────────────────────────────
# USB resource strings are auto-generated by the VISA layer from the device's
# VID, PID, and serial number. Use list_resources() above to find the exact string.
KEITHLEY_ADDRESS = "USB0::0x05E6::0x2230::1234567::INSTR"  # replace serial

keithley_resource = rm.open_resource(KEITHLEY_ADDRESS)
keithley_resource.timeout = 30000
print("Keithley IDN:", keithley_resource.query("*IDN?").strip())

# ── LAN connection — Keysight power supply ────────────────────────────────────
KEYSIGHT_SUPPLY_ADDRESS = "TCPIP0::192.168.1.102::inst0::INSTR"

ks_supply_resource = rm.open_resource(KEYSIGHT_SUPPLY_ADDRESS)
ks_supply_resource.timeout = 30000
print("Keysight Supply IDN:", ks_supply_resource.query("*IDN?").strip())

# ── Always close resources when done ─────────────────────────────────────────
scope_resource.close()
siggen_resource.close()
keithley_resource.close()
ks_supply_resource.close()
rm.close()
